### ISSUE TITLE
Installation issues (readme enhancements)

### ISSUE THREAD

**Issue by CBDev1** [Beanstream/beanstream-ios-payform#2]
I am having issues following the readme. So far I am able to install cocoapods 1.0.1 and cocoapods-art plugin just fine.

Problem 1. However, running pod install on the indicated podfile contents results in an error: repo bic-pods-local does not exist. 

Problem 2. I tried changing it to beanstream-public (since that was the artifactory repo we were just told to install) and it gets past that error to a new one: Unable to find a specification for `PayForm`

Problem 3. The note below the podfile contents should read: Note that 'pod update' alone does not update Artifactory based pod indexes as expected and use 'pod repo-art update **beanstream-public**' first and then use 'pod update'.

Problem 4. I am unable to run the sample project because of swift version used. The readme file should indicate which verison of xcode was last used to build the project.

Thanks for any help!

**Comment by svenresch** [comment]
Hi CBDev1. Thx very much for all your comments!!

I have updated the readme to to fix up the name issues. I have also added the following to the readme. "This project was compiled with Xcode 7.3.1 and uses Swift 2.2." What version of Xcode are you on?

Even after the fixes do you still get the "Unable to find a specification for PayForm" error?

**Comment by CBDev1** [comment]
I have xcode 7.2.1, so I will update to get Swift 2.2

As for the podfile, my current error is "Unable to find a specification for `PayForm`"

and actually it fails on whatever I put as the first pod when this line is in the podfile:

plugin 'cocoapods-art', :sources => [
  'beanstream-public'
]

not sure what I might be doing wrong. I have cocoapods 1.0.1 and followed the first 2 lines to install cocoapods-art and beanstream-public repo-art

**Comment by svenresch** [comment]
Ok. Working on setting up a new clean environment to double check install steps and to see if we can reproduce the same issue. Thx for your patience.

**Comment by svenresch** [comment]
@CBDev1 Found that there was a permissions issue with anonymous access on beanstream-public. This problem has now been fixed. Sorry for the inconvenience and thx again for point out the issue.

**Comment by CBDev1** [comment]
@svenresch Thanks for the help! 

Two more things that can be added to the Instructions:

1. The plugin source overrides the normal cocoapods source, so this line needs to be added to the top of the podfile if any normal cocoapods are used:
source 'https://github.com/CocoaPods/Specs.git'

2. It is also a requirement that the cocoapods deployment target is set to 8.2 or higher (is there any reason the PayForm library cannot support 8.0 and up?):
platform :ios, "8.2"
